# Dev configuration

server:
  rootPath: '/rest/*'

  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO

  loggers:
    ru.vyarus.app.todo: INFO

